#323 trailer icon for external reference links
openworm/geppetto-client pull request #324
Opened 2020-07-20 22:44 UTC by ddelpiano

2020-08-18 09:31 UTC, filippomc approved these changes
Do we really need this ad-hoc functionality? Why just not include the trailer icon in the label from the application? Or change the order of the icon that we already have?

2020-08-18 09:31 UTC, filippomc commented on js/components/interface/menu/MenuSingleItem.js
> +            ? <i style={{ marginLeft: "5px" }} className={item.trailerIcon}></i>
Better remove the inline margin

2020-08-18 10:43 UTC, ddelpiano commented
> Do we really need this ad-hoc functionality? Why just not include the trailer icon in the label from the application? Or change the order of the icon that we already have?

@filippomc to be honest I thought about that but the label is defined as a string in the json, are you thinking about editing the json before the menu it's rendered and then add the object there?

2020-08-18 11:52 UTC, filippomc commented
> > Do we really need this ad-hoc functionality? Why just not include the trailer icon in the label from the application? Or change the order of the icon that we already have?
> 
> @filippomc to be honest I thought about that but the label is defined as a string in the json, are you thinking about editing the json before the menu it's rendered and then add the object there?

I'm already using react component labels to replace the label with an icon and it's working well:

```javascript
{
      label: <span><SvgIcon name='eye' /><sub style={{ marginLeft: 2 }}><i className="fa fa-angle-down" /></sub></span>,
      icon: "",
     ...
    }
```
If there are use cases with a pure json file then I agree we need the feature. In that case, I think it's to better remove inline css and add an example of use to the showcase.

2020-08-18 11:54 UTC, filippomc commented
Other imporant  thing to consider is we are more and more needing non-font icons in the new application design so the usual fontawesome class approach can be a strong limitation

2020-08-18 11:56 UTC, filippomc requested changes
Suggested changes:

- remove inline css
- reconsider font-based approach to display the icon

2020-08-25 15:20 UTC, tarelli commented
@ddelpiano waiting on you when you get a chance

2020-09-23 10:47 UTC, filippomc commented
@ddelpiano I guess this is outdated after https://github.com/openworm/geppetto-client/pull/333

2020-09-28 14:21 UTC, closed without merging