Feature/218
openworm/geppetto-client pull request #332
Opened 2020-08-26 09:27 UTC by afonsobspinto

closes #218 

Canvas Summary:

- Use data prop to define the (Proxy) Instances to visualize
- Use cameraOptions prop to define camera configuration attributes and potentially absolute camera position and rotation
- Use threeDObjects prop to define additional threeJS objects to be added to a scene (e.g. 3D plane) 
- You can have access to the scene using the onMount prop
- Camera and Selection changes are passed through cameraHandler and selectionHandler props.
- Additional props like linesThreshold, backgroundColor and hoverListeners, are also functional^
- Visual Groups can be achieved by specifying in the data prop object the attribute visualGroups:
```
visualGroups: {
            index: 0,
            custom: {
              soma_group: { color: COLORS[0], },
              dendrite_group: { color: COLORS[1], },
              axon_group: { color: COLORS[2], },
            },
          },
```
which requires the index (at Geppetto model level) of the visualGroup to show or/and a custom color definition.
- Show the connection lines of an instance can be achieved by setting the attribute showConnectionLines of an instance, in the data prop, to true
- You can opt in or out for having camera controls by setting or not the attribute cameraControls of cameraOptions prop:
```
        cameraControls: { 
          instance: CameraControls,
          props: { wireframeButtonEnabled: false, }
        },
``` 

Questions/Notes/Issues:
- Currently, camera updates based on cameraHandler callbacks on VFB example are disabled due to an issue with flipping the camera.
- How to properly define default incrementPan if cameraOptions prop is defined but not contain that attribute?
- ThreeDEngine should receive props instead of the chain of parameters currently implemented
- Test the modelVersion prop needed to propagate updates on async changes (import types)

2020-09-02 15:58 UTC, filippomc requested changes
@afonsobspinto I did a local test with the showcase and looks great. Still I think we need to improve the performance when loading the tab of the canvas, the time it takes is not too bad but looks stuck.

2020-09-02 16:03 UTC, filippomc commented on geppetto-ui/src/3d-canvas/showcase/examples/AuditoryCortexExample.js
> +import model from './model.json';
This may be moved after the component is rendered (componentDidMount shoud work)

2020-11-17 16:12 UTC, tarelli commented
@afonsobspinto a reminder for this in a few weeks time once we have bandwidth again

2021-01-26 16:29 UTC, afonsobspinto commented
Due date: First week february @afonsobspinto

2021-02-18 18:41 UTC, afonsobspinto commented
Model.json makes the bundle size too big:
![image](https://user-images.githubusercontent.com/19196034/108405341-e31c5b00-7218-11eb-8417-b005d5b02cc9.png)
[geppetto-website [18 Feb 2021 at 18_36].zip](https://github.com/openworm/geppetto-client/files/6005067/geppetto-website.18.Feb.2021.at.18_36.zip)

2021-02-25 10:44 UTC, afonsobspinto reviewed
Some issues on the comments:

2021-02-25 10:51 UTC, afonsobspinto commented
There's a prop called zoom to which focus the camera on the instances passed.
If I move around and trigger a new render, I need to remove the zoom to prop so that the camera stays in the same position/rotation. This is the expected behavior correct? 
If I do not remove we will see things like:
![Peek 2021-02-25 10-49](https://user-images.githubusercontent.com/19196034/109142940-5f51f980-7757-11eb-8991-69155b2bf8b4.gif)

2021-02-25 10:53 UTC, afonsobspinto commented
VFB model is not centered. This makes the camera movement less intuitive. (Axis on the top left shows the scene center)
![image](https://user-images.githubusercontent.com/19196034/109143118-94f6e280-7757-11eb-8cf2-8618ba97515f.png)

2021-02-25 11:40 UTC, afonsobspinto commented
Selection handler logic seems to have some flaws on vfb showcase. 
It only happens with "VFB_00030624" instance (potentially because there are two instances that contain that path) where color says blue and we see yellow instead.
![image](https://user-images.githubusercontent.com/19196034/109147896-75fb4f00-775d-11eb-8e67-1a2ca6beaada.png)
![image](https://user-images.githubusercontent.com/19196034/109147931-814e7a80-775d-11eb-8934-1ab7e15404d1.png)

2021-02-25 11:41 UTC, afonsobspinto commented
cameraHandler gets camera position and rotation a few frames behind.
This causes small jumps on new render calls (for example upon selection):

![Peek 2021-02-25 10-41](https://user-images.githubusercontent.com/19196034/109142036-4bf25e80-7756-11eb-91b6-515de4c4874b.gif)

![image](https://user-images.githubusercontent.com/19196034/109141342-89a2b780-7755-11eb-9f28-884f8e87fdb2.png)

2021-04-06 15:52 UTC, afonsobspinto commented
- [ ] Try to set the camera.up to the 'normal' vector before the update camera flips

2024-12-19 11:33 UTC, closed without merging